---
- hosts: localhost
  tasks: 
    - name: Uninstall OpenJDK
      become: yes
      become_method: sudo
      yum: name=java-1.8.0-openjdk-headless.x86_64 state=absent  update_cache=yes

#
#      when:  "'$ansible_pkg_mgr' == 'yum'"
#  
#    - name: Uninstall OpenJDK
#      become: yes
#      become_method: sudo
#      apt: name=java-1.8.0-openjdk-headless.x86_64 state=absent
#      when: "'$ansible_pkg_mgr' == 'apt'"
  
