---
- name: Install OpenJDK
  yum: name=java-1.8.0-openjdk-headless.x86_64 state=present

- name : Download Kafka
  get_url: url="http://www.mirrorservice.org/sites/ftp.apache.org/kafka/{{ kafka_version }}/kafka-{{ kafka_version }}-src.tgz" dest="/tmp/kafka-{{ kafka_version }}-src.tar.gz mode=0644 force=no"

- name : Unpack Kafka
  shell: "tar -xzvf /tmp/kafka-{{ kafka_version }}-src.tar.gz chdir=/tmp/ creates=/tmp/kafka-{{ kafka_version }}-src"
  
- name: run SBT update
  shell: "sbt update chdir=/tmp/kafka-{{ kafka_version }}-src creates=/usr/local/kafa-{{ kafka_version }}"

- name: run SBT package
  shell: "sbt package chdir=/tmp/kafka-{{ kafka_version }}-src creates=/usr/local/kafa-{{ kafka_version }}"

- name: Copy Kafka into place
  shell: "mv /tmp/kafka-{{ kafka_version }}-src /usr/local/kafa-{{ kafka_version }} creates=/usr/local/kafa-{{ kafka_version }}"

  
- name: Symlink /usr/local/kafka to this version
  shell: "ln -s kafa-{{ kafka_version }} kafka chdir=/usr/local creates=/usr/local/kafka"

- name: Run Gradle to build Kafka
  shell: ./gradlew jar chdir=/usr/local/kafka creates=/usr/local/kafka/core/build/

#- name: Install the Kafka service handler
#  copy: src=init.d/kafka dest=/etc/init.d/ mode=0755
