---
  - name: Install kafka
    vars:
      is_kafka_server: "{{ lookup('env','IS_KAFKA_SERVER') }}"
    include: install-kafka.yml
    when: ( "{{ lookup('env','IS_KAFKA_SERVER') }}" is defined and "{{ is_kafka_server }} == true")

  - name: Runk kafka and zookeper as services
    include: kafka-service.yml

  - name: Run kafka
    include: run-kafka.yml
