#! /bin/sh

## BEGIN INIT INFO
# chkconfig: - 85 15
# pidfile: /var/run/kafkad/kafkad.pid
# Provides:		kafka
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Kafka daemon
# processname: kafkad
## END INIT INFO

#set -e

export KAFKA_HOME=/usr/local/kafka

PROCESS="$(pgrep -x kafkad)"

# /etc/init.d/kafka: start and stop the Kafka daemon

. /etc/init.d/functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}


do_start() {
    if [ "$PROCESS" = "" ] ; then
#   	echo -n $"Starting kafka...";
        echo -n $"starting Kafka from path "$KAFKA_HOME
#	log_daemon_msg "Starting Kafka" "kafka" || true
#        "$KAFKA_HOME/bin/kafka-server-start.sh" "-daemon" "$KAFKA_HOME/config/server.properties"
#        log_end_msg 0 || true
    else
        echo -n $"kafka already running."
    fi
    echo " "
}

do_stop() {
    if [ "$PROCESS" != "" ] ; then
   	echo -n $"Stopping kafka.";
#	log_daemon_msg "Stopping Kafka" "kafka" || true
        ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep |  awk '{print $1}' | xargs kill -SIGKILL
#	log_end_msg 0 || true
    else
        echo -n $"kafka is not running."
    fi
    echo " "
}

do_status()
{
#    status_of_proc -p /var/run/kafka.pid && exit 0 || exit $?
    if [ "$PROCESS" = "" ] ; then
        echo -n $"kafka not running."
    else
        echo -n $"kafka is currently running. PID:"
        echo -n $"$PROCESS "
    fi
    echo " "
}

do_wait()
{
   while [ "$PROCESS" != "" ]
   do
       sleep 0.1
   PROCESS="$(pgrep -x kafkad)"
   done  
}


case "$1" in
   start)
	echo $PROCESS
     do_start
     ;;
   stop)
     do_stop
     ;;
   status)
     do_status
     ;;
   restart)
     do_stop
     do_wait
     do_start
     ;;
  *)
#     log_action_msg "Usage: /etc/init.d/ssh {start|stop|status}" || true
     echo -n $"Usage: /etc/init.d/ssh {start|stop|status}" || true
     echo ""
     exit 1
esac



#export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
#
#case "$1" in
#  start)
#        echo "starting Kafka from path "$KAFKA_HOME
#	log_daemon_msg "Starting Kafka" "kafka" || true
#        "$KAFKA_HOME/bin/kafka-server-start.sh" "-daemon" "$KAFKA_HOME/config/server.properties"
#        log_end_msg 0 || true
#	;;
#  stop)
#	log_daemon_msg "Stopping Kafka" "kafka" || true
#        ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep |  awk '{print $1}' | xargs kill -SIGKILL
#	log_end_msg 0 || true
#	;;
#
#  status)
#	status_of_proc -p /var/run/kafka.pid && exit 0 || exit $?
#	;;
#
#  *)
#	log_action_msg "Usage: /etc/init.d/ssh {start|stop|status}" || true
#	exit 1
#esac

exit 0
